### GET request with parameter
GET http://localhost:8087/api/convert?from=BG&to=EUR&amount=50
Accept: application/json

### GET request with parameter
GET http://localhost:8087/offers/1
Accept: application/json